name: cosmicrafts_com

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '21'

    - name: Install Dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        REMOTE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Use the SSH private key secret
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.SERVER_IP }}
        REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
        TARGET: "/var/www/cosmicrafts.com"
